Added an override function for the partner chain id
OffchainLabs/arbitrum-sdk pull request #143
Opened 2022-08-09 17:22 UTC by yahgwai

2022-08-09 17:33 UTC, fredlacs approved these changes
LGTM

2022-08-10 09:44 UTC, gzeoneth requested changes
I think we can drop `lastUpdatedL1` and cache `isNitro` and `lastUpdatedL2` per L2 chain ID (may be in the network entity object), then in `isNitroL1()` we first get the partner L2 and use its `lastUpdatedL2` so we can avoid a lot of rpc call to `isNitro` functions when you switch between network frequently.

2022-08-10 13:56 UTC, gzeoneth approved these changes

2022-08-10 13:56 UTC, fredlacs commented
this version got already published, but good concerns raised.
lets address in a follow up PR?

2022-08-10 13:56 UTC, merged