feat: update `depositTo` to use standard deposit
OffchainLabs/arbitrum-sdk pull request #432
Opened 2024-03-19 11:19 UTC by brtkx

2024-03-19 11:49 UTC, gzeoneth requested changes

2024-03-19 11:49 UTC, gzeoneth commented on src/lib/assetBridger/ethBridger.ts
> +    const tx = await inbox.connect(params.l1Signer).unsafeCreateRetryableTicket(
why are we using `unsafeCreateRetryableTicket` here? can be dangerous

2024-03-19 11:57 UTC, gzeoneth approved these changes
LGTM

2024-03-19 15:18 UTC, gzeoneth requested changes

2024-03-19 15:18 UTC, gzeoneth commented on src/lib/assetBridger/ethBridger.ts
> +        value: amount,
actually this should be
```suggestion
        value: gasEstimation.deposit,
```

2024-04-16 10:27 UTC, gzeoneth approved these changes
LGTM

2024-04-30 16:01 UTC, spsjvc commented on tests/integration/eth.test.ts
> +    let l1ToL2Message = l1ToL2Messages[0]
```suggestion
    const l1ToL2MessageReader = l1ToL2Messages[0]
```

2024-04-30 16:01 UTC, spsjvc commented on tests/integration/eth.test.ts
> +    }
```suggestion
    const l1ToL2MessageWriter = l1Receipt.getL1ToL2Messages(l2Signer)[0]

    await (await l1ToL2MessageWriter.redeem()).wait()
```

2024-04-30 17:07 UTC, spsjvc approved these changes
LGTM

2024-04-30 17:12 UTC, merged